# Generated by Django 3.0.4 on 2020-03-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200305_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(null=True, related_name='books', to='api.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='books', to='api.Category'),
        ),
        migrations.DeleteModel(
            name='BookCategory',
        ),
    ]
